### ISSUE TITLE
TP07: App Architecture

### ISSUE THREAD

**Issue by MuhammadRidwan4404** [indraazimi/hitung-bmi#1]
1.	● Mendefinisikan dengan jelas di mana logika bisnis tertentu berada
● Memudahkan pengembang untuk berkolaborasi
● Membuat kode Anda lebih mudah untuk diuji
● Memungkinkan Anda mendapatkan keuntungan dari masalah yang sudah dipecahkan 
● Menghemat waktu dan mengurangi utang teknis saat Anda memperluas aplikasi Anda
2.	View Model adalah sebuah kelas yang dirancang untuk menyimpan dan mengelola data yang diasanya berhubungan denganUI.
Kelebihan View Model
• Ketika kita menggunakan arsitektur MVC akan memisahkan user interface dari logika bisnis, logika bisnis dari logika akses data. Jadi arsitektur MVC akan meningkatkan fleksibilitas, pemeliharaan dan skalabilitas. 
• Arsitektur MVC model memudahkan kita dalam me-maintain dan pengembangan aplikasi. 
• Dalam Arsitektur MVC kita dapat membuat komponen yang berbeda dari aplikasi yang dapat kita kembangkan sendiri meskipun saat ini belum digunakan.
• Arsitektur MVC juga membantu kita untuk menguji komponen secara bebas tidak tergantung dari kelas lain.
Kekurangan View Model
• Pengembangan aplikasi akan lebih lama karena banyak layer yang harus dibuat. 
• Kompleksitas kode semakin tinggi, sehingga tidak cocok untuk aplikasi yang sederhana. 
• Memungkinkan akan membutuhkan lebih banyak programmer. 
• Pengetahuan terhadap beberapa teknologi sangat dibutuhkan
3.	•  LiveData adalah Pemegang data sadar siklus hidup yang dapat diamati
•  Observer Design Pattern adalah pola desain perilaku di mana objek direpresentasikan sebagai pengamat yang menunggu peristiwa untuk memicu. Ketika peristiwa baru dipicu, beberapa pengamat menangkap peristiwa ini.
4.	• Data Binding adalah proses membangun koneksi antarmuka aplikasi  dan business logic. Data binding membuat kontrol-kontrol dalam form terkoneski dengan sumber-smber data.
•View binding dan data binding keduanya menghasilkan class binding yang dapat Anda gunakan untuk mereferensikan tampilan secara langsung. Namun, view binding ditujukan untuk menangani kasus penggunaan yang lebih sederhana dan memberikan manfaat berikut dibandingkan data binding:
•	Kompilasi yang lebih cepat: View binding tidak memerlukan pemrosesan anotasi, sehingga waktu kompilasi menjadi lebih cepat.
•	Kemudahan penggunaan: View binding tidak memerlukan file tata letak XML yang diberi tag khusus, sehingga lebih mudah untuk diterapkan di aplikasi Anda. Setelah Anda mengaktifkan view binding dalam modul, view binding akan diterapkan ke semua tata letak modul tersebut secara otomatis.
Sebaliknya, view binding memiliki batasan berikut dibandingkan dengan data binding:
•	View binding tidak mendukung variable tata letak atau ekspresi tata letak, sehingga tidak dapat digunakan untuk mendeklarasikan konten UI dinamis langsung dari file tata letak XML.
•	View binding tidak mendukung data binding dua arah.

**Comment by indraazimi** [comment]
TP dikerjakan di issue repository praktikum masing2, bukan di repo ini. Praktikum modul 7 dikerjakan di repository modul 5. Selengkapnya baca bagian Getting Started di modul.
